branch-defaults:
  aa/pipeline_modifications:
    environment: null
    group_suffix: null
  development:
    environment: beiweCluster-staging
  master:
    environment: beiweCluster-staging
  production:
    environment: beiweCluster-production
global:
  application_name: Beiwe Cluster
  default_ec2_keyname: new_beiwe_key_pair
  default_platform: 64bit Amazon Linux 2018.03 v2.7.0 running Python 2.7
  default_region: us-east-1
  profile: eb-cli
  sc: git
